config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
# Inside FlatsController
class FlatsController < ApplicationController

def index
  @flats = Flat.all
end

def new
  @flat = Flat.new
end

def create
  @flat = Flat.new(flat_params)
  if @flat.save
    redirect_to flat_path(@flat)
  else
    render :new
  end
end


# Inside FlatsController

def edit
  @flat = Flat.find(params[:id])
end

def update
  @flat = Flat.find(params[:id])
  if @flat.update(flat_params)
    redirect_to flat_path(@flat)
  else
    render :edit
  end
end


def show
  @flat = Flat.find(params[:id])
end

# Inside FlatsController

def destroy
  @flat = Flat.find(params[:id])
  @flat.destroy
  redirect_to flats_path
end



private

def flat_params
  params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<!-- app/views/flats/_form.html.erb -->
<%= form_with model: @flat do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :price_per_night %>
    <%= form.number_field :price_per_night, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :number_of_guests %>
    <%= form.number_field :number_of_guests, class: "form-control" %>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<!-- app/views/flats/edit.html.erb -->
<h1>Edit Flat</h1>
<%= render 'form', flat: @flat %>

app/views/flats/index.html.erb
<!-- app/views/flats/index.html.erb -->
<div class="container mt-4">
  <h1 class="mb-4">Available Flats</h1>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-md-4 mb-3">
        <div class="card">
          <%= image_tag flat.picture_url, alt: flat.name, class: "card-img-top" if flat.picture_url.present? %>
          <div class="card-body">
            <h5 class="card-title"><%= flat.name %></h5>
            <p class="card-text"><%= flat.description %></p>
            <p class="card-text"><strong>Price per night:</strong> <%= flat.price_per_night %></p>
            <p class="card-text"><strong>Number of guests:</strong> <%= flat.number_of_guests %></p>
            <%= link_to 'View Details', flat_path(flat), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<!-- app/views/flats/new.html.erb -->
<h1>Add a New Flat</h1>

<!-- app/views/flats/new.html.erb -->
<h1>Add a New Flat</h1>
<%= render 'form', flat: @flat %>


<%= form_with model: @flat do |form| %>
  <%= form.text_field :name %>
  <%= form.text_field :address %>
  <%= form.text_area :description %>
  <%= form.number_field :price_per_night %>
  <%= form.number_field :number_of_guests %>
  <%= form.submit %>
<% end %>

app/views/flats/show.html.erb
<!-- app/views/flats/show.html.erb -->
<h1><%= @flat.name %></h1>
<p><%= @flat.description %></p>
<!-- Add more details here -->
<!-- app/views/flats/show.html.erb -->
<h1><%= @flat.name %></h1>
<!-- Flat details here -->
<%= link_to 'Edit', edit_flat_path(@flat), class: 'btn btn-secondary' %>
<%= link_to 'Back to Flats', flats_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>